### ISSUE TITLE
Relax tslint rules or use Javascript

### ISSUE THREAD

**Issue by D4nte** [comit-network/hello-swap#34]
## Problem

During a workshop/live coding, the linter is cumbersome, especially around unused imports and variables/arguments.
However, we want to keep the hello-swap codebase to a high quality level.

## Goal

Only apply linter when we modify the hello-swap codebase, not when it is used as part of a new project

## Recommendation

Steps:
1. Relax the rules in the default/shipped `tslint.json`.
2. Create a new `tslint-strict.json` file that is used during the CI and commit hooks

**Comment by D4nte** [comment]
Findings: none because `tsc` uses options in `tsconfig.json` so both `tsconfig` and `tslint` files should be modified.

**Comment by da-kami** [comment]
Issue moved to [comit-network/create-comit-app #89](https://github.com/comit-network/create-comit-app/issues/89) via [**ZenHub**](https://www.zenhub.com/)
