### ISSUE TITLE
Add CI check

### ISSUE THREAD

**Issue by D4nte** [comit-network/hello-swap#39]
## Problem

There is no CI hence no guaranteed that a change does not break it.

## Goal

Create a CI test

## Recommendation

Add the following steps to the CI:
```
- sh ./.githooks/pre-commit
- sh test.sh
```

With `test.sh` file:

```
curl a released version of `create-comit-app`
unpack it
create-comit-app start-env > start-env.log 2>&1 &
yarn run
check success
pkill yarn
pkill create-comit-app
```

**Comment by luckysori** [comment]
Closed because we're moving this project into create-comit-app.
