### ISSUE TITLE
Remove Swap-ID from printout

### ISSUE THREAD

**Issue by da-kami** [comit-network/hello-swap#5]
At the moment 2 different SWAP IDs are generated for the 2 actors, this feels weird when reading it in log-output:
```
[charlie] swap accepted: 1fb513ed-dfc4-4c38-863d-f17368389014
[david] Funding bitcoin for "ee7a6ccf-05e6-45de-99be-e0802fbd9231"
```

I feel it's tough for the user to make the connection that this is actually the same swap with different IDs (for each side). This won't be a problem if/once we change the swap ID to be deterministic, but for now it's probably better to just say "swap" (or specify some classifier that explains that it is per actor).

**Comment by luckysori** [comment]
Closed because we want to generate the swap ID deterministically now.
