### ISSUE TITLE
Add counterparty name to the printout when sending a swap

### ISSUE THREAD

**Issue by da-kami** [comit-network/hello-swap#6]
I feel it would be nice to state the counterparty's name when sending a swap. The peer-id alone is tough to understand.

at the moment the output is:
```
[david] Sending offer to: QmRrCNaQneFRRQcURgoMPqbVJ5QLFCwmmKZEcxnWGTwCmx
```

could we make it:
```
[david] Sending offer to [charlie] @ QmRrCNaQneFRRQcURgoMPqbVJ5QLFCwmmKZEcxnWGTwCmx
```

It would help when reading the output, but probably is not really confirm to the behavior (because we don't necessarily know the actual identity of the other party).

**Comment by luckysori** [comment]
Will be tackled in #4.
