### ISSUE TITLE
Hello-World shutdown/end behaviour

### ISSUE THREAD

**Issue by da-kami** [comit-network/hello-swap#7]
At the moment we have to kill the Hello-World with `ctrl + C` because there is no automatic end. The user can do multiple swaps. 

There are several issues attached to that: 
1. We only print the final balance once the user exits with `ctrl + C`, I think we should print the balances after each turn.
2. There is no "step" that explains to the user that he can go again.
3. Avoid printing `SIGINT` in log when we exit

We should probably re-discuss the shutdown/end constraints of the Hello-World example.

**Comment by D4nte** [comment]
I don't see a technical way to go around this.
1. Balance can be printed at redeem time if it's preferred
2. What do you mean?
3. I don't think it's possible
